apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vkr2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vkr2
    app.kubernetes.io/part-of: tkwch-fix-0075-0002-app
  name: devfile-sample-vkr2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vkr2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vkr2
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0002-tenant/tkwch-fix-0075-0002-app/devfile-sample-vkr2@sha256:61fce33c9d9c3732b0c7f96881fd695577cc6b9838124ec2229d908bc6722870
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
